package org.fnm.simulator;

import io.quarkus.scheduler.Scheduled;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import net.ihe.gazelle.servicemetadata.api.business.Service;
import net.ihe.gazelle.simulation.business.callback.*;
import net.ihe.gazelle.simulation.business.sequence.*;
import net.ihe.gazelle.simulation.business.setup.*;
import org.fnm.simulator.simulations.clientCredentials.HelloGazelleSimulationConfig;
import org.fnm.simulator.simulations.clientCredentials.HelloGazelleSimulation;
import org.fnm.simulator.simulations.Status;
import org.jboss.logging.Logger;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The core simulation service, and the one class a simulator has to write. It implements the two
 * business interfaces of the Gazelle simulation framework:
 * <ul>
 *   <li>{@link SimulationSequenceService} -- the sequences this simulator offers;</li>
 *   <li>{@link SimulationService} -- {@code setup} prepares a session, {@code runSimulation} performs it
 *       and hands the report to the {@link SimulationCallback} it is given.</li>
 * </ul>
 * Session ids, the simulation timeout and delivering the report to the callback URL are left to the
 * Gazelle simulation manager, see {@link HelloGazelleSimulationManagerFactory}.
 */
@ApplicationScoped
public class HelloGazelleSimulationService implements SimulationService, SimulationSequenceService {

    private static final Logger LOG = Logger.getLogger(HelloGazelleSimulationService.class);

    public static final String SEQUENCE_ID = "001";

    @Inject
    HelloGazelleMetadataService metadataService;

    private final Map<String, HelloGazelleSimulation> simulations = new ConcurrentHashMap<>();

    /**
     * @return the simulation sequences this simulator supports
     */
    @Override
    public List<SimulationSequence> getSimulationSequences() {
        return List.of(getHelloGazelleSimulationSequence());
    }

    /**
     *
     * @param sessionId         unique identifier of this simulation run, generated by the simulation manager.
     * @param simulationRequest the information required for a single simulation run
     * @return the SetupOutcome
     * @throws UnknownSequenceException if the sequence is not one of this simulator's
     */
    @Override
    public SetupOutcome setup(String sessionId, SimulationRequest simulationRequest) {

        String sequenceId = simulationRequest.getSequenceId();

        if (sequenceId.equals(SEQUENCE_ID)) {

            HelloGazelleSimulationConfig config = new HelloGazelleSimulationConfig(sessionId, simulationRequest);
            simulations.put(sessionId, new HelloGazelleSimulation(config));

            // return "ready to go". The simulationId is what the requester will call resume with,
            // so it has to be the session id this simulation is registered under.
            AdditionalInstructions additionalInstructions = new AdditionalInstructions();
            additionalInstructions.setSimulationId(sessionId);

            String message = "Test for the hello gazelle simulator is initialized and can be started! ";
            additionalInstructions.setInstruction(message);
            return additionalInstructions; // new SwitchToExecution();
        }

        throw new UnknownSequenceException();

    }

    /**
     * Runs the simulation set up under the session id and delivers its report through the callback.
     * <p>
     * The simulation manager calls this on a thread of its own and cancels that thread once the timeout
     * requested at setup has passed, reporting the timeout itself. A run cancelled that way sends
     * nothing: its report would be a second one for the same session.
     *
     * @param sessionId the current test session id
     * @param callback  callback to be notified when the simulation is finished
     */
    @Override
    public void runSimulation(String sessionId, SimulationCallback callback) {

        // a simulation runs at most once, so it leaves the map as it starts
        HelloGazelleSimulation simulation = simulations.remove(sessionId);
        if (simulation == null) {
            throw new UnknownSimulationException(UnknownSimulationException.BASE_MESSAGE + sessionId);
        }

        LOG.info("Running hello gazelle simulation with session id " + sessionId);

        TransactionReport transactionReport = simulation.run();

        // build the report
        Service service = metadataService.getMetadata();

        SimulationReport simulationReport = new SimulationReport();
        simulationReport.setUuid(sessionId);
        simulationReport.setSequenceId(simulation.getConfig().sequenceId);
        simulationReport.setServiceName(service.getName());
        simulationReport.setDateTime(Instant.now());
        simulationReport.setResult(transactionReport.getResult());
        simulationReport.setTransactionReports(List.of(transactionReport));
        simulationReport.setServiceVersion(service.getVersion());
        simulationReport.setSimulationParameters(simulation.getConfig().simulationParameters);

        LOG.info("Finished hello gazelle simulation with session id " + sessionId);

        if (Thread.currentThread().isInterrupted()) {
            LOG.warn("Simulation with session id " + sessionId + " was cancelled after its timeout, its report is not sent");
            return;
        }

        callback.notifySimulation(simulationReport);
    }

    /**
     * Periodically removes simulations that were set up but never resumed. A simulation that is
     * resumed leaves the map when it starts running.
     */
    @Scheduled(every = "10s")
    void run() {

        // accepted age of simulations before being removed
        long acceptedDelayInSeconds = 10 * 60;

        for (Map.Entry<String, HelloGazelleSimulation> entry : simulations.entrySet()) {

            String sessionId = entry.getKey();
            HelloGazelleSimulation simulation = entry.getValue();

            // orphaned simulations
            if (simulation.status == Status.READY &&
                    simulation.getCreatedAt().plusSeconds(acceptedDelayInSeconds).isBefore(Instant.now())) {
                LOG.info("Remove orphaned simulation with sessionId = " + sessionId + " and timestamp = " + simulation.getCreatedAt());
                simulations.remove(sessionId, simulation);
            }
        }
    }

    /**
     * @return the SimulationSequence definition for the hello gazelle simulation
     */
    public SimulationSequence getHelloGazelleSimulationSequence() {

        SimulationSequence sequence = new SimulationSequence();
        sequence.setId(SEQUENCE_ID);

        SupportedParameter message = new SupportedParameter();
        message.setName("message").setGroupName("Sequence settings").setType(ParameterType.TEXT);
        message.setDefaultValue("Hello Gazelle!").setRequired(true);
        message.setDescription("The message to be printed to the console.");

        // add parameter to the sequence
        sequence.setSupportedParameters(List.of(message));

        sequence.setTransactions(List.of("LOG To console"));
        sequence.setShortDescription("Sequence for the hello gazelle simulation.");
        sequence.setDescription("Sequence for the hello gazelle simulation. In this sequence, the SUT specifies a message in the simulation setup and the simulator prints the message to the console.");

        sequence.setStandards(List.of("UTF-8"));

        // add the tested role
        TestedRole testedRole = new TestedRole();
        testedRole.setName("Hello Gazelle system under test");
        testedRole.setType(RoleType.INITIATOR);
        sequence.setTestedRoles(List.of(testedRole));

        // add the simulationRole
        SimulatedRole simulationRole = new SimulatedRole();
        simulationRole.setName("Hello Gazelle simulator");
        simulationRole.setType(RoleType.RESPONDER);
        sequence.setSimulatedRoles(List.of(simulationRole));

        LOG.info("Return the hello gazelle simulator sequence: " + sequence);
        return sequence;
    }
}
