package org.fnm.simulator;

import io.quarkus.scheduler.Scheduled;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import net.ihe.gazelle.servicemetadata.api.business.Service;
import net.ihe.gazelle.simulation.business.callback.*;
import net.ihe.gazelle.simulation.business.sequence.*;
import net.ihe.gazelle.simulation.business.setup.*;
import net.ihe.gazelle.simulation.business.setup.Parameter;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.fnm.simulator.helper.SigningKeyHelper;
import org.fnm.simulator.simulations.authorizationCode.AuthorizationCodeConfig;
import org.fnm.simulator.simulations.authorizationCode.AuthorizationCodeSimulation;
import org.fnm.simulator.simulations.clientCredentials.ClientCredentialConfig;
import org.fnm.simulator.simulations.clientCredentials.ClientCredentialsSimulation;
import org.fnm.simulator.simulations.Status;
import org.jboss.logging.Logger;

import java.text.ParseException;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The core simulation service. It declares the simulation sequences and runs the individual simulations.
 * <p>
 * Session ids, the simulation timeout and delivering the report to the callback URL are left to the
 * Gazelle simulation manager, see {@link IUAClientSimulationManagerFactory}.
 */
@ApplicationScoped
public class IUAClientSimulationService implements SimulationService, SimulationSequenceService {

    private static final Logger LOG = Logger.getLogger(IUAClientSimulationService.class);

    public static final String CLIENT_CREDENTIAL_SEQUENCE_ID = "c74f063b-fb76-405e-8fa3-b2632b5c112f";
    public static final String AUTHORIZATION_CODE_SEQUENCE_ID = "0064e130-cf31-40f5-ad62-163af639b360";

    @ConfigProperty(name = "redirectUri")
    String redirectUri;

    @Inject
    IUAClientMetadataService metadataService;

    private final Map<String, ClientCredentialsSimulation> clientCredentialSimulations = new ConcurrentHashMap<>();
    private final Map<String, AuthorizationCodeSimulation> authorizationCodeSimulations = new ConcurrentHashMap<>();

    private static final String SPID = "761337610411353650^^^&2.16.756.5.30.1.127.3.10.3&ISO";

    /**
     * @return the simulation sequences this simulator supports
     */
    @Override
    public List<SimulationSequence> getSimulationSequences() {
        return List.of(getClientCredentialSequence(), getAuthorizationCodeSequence());
    }

    /**
     *
     * @param sessionId unique identifier of this simulation run, generated by the simulation manager.
     * @param simulationRequest the information required for a single simulation run
     * @return the SetupOutcome
     * @throws MissingRequiredParameterException if the request does not configure the sequence completely
     * @throws UnknownSequenceException if the sequence is not one of this simulator's
     */
    @Override
    public SetupOutcome setup(String sessionId, SimulationRequest simulationRequest) {

        String sequenceId = simulationRequest.getSequenceId();

        if (sequenceId.equals(CLIENT_CREDENTIAL_SEQUENCE_ID)) {

            ClientCredentialConfig config = new ClientCredentialConfig(sessionId, simulationRequest);
            assertValid(config.validate());

            clientCredentialSimulations.put(sessionId, new ClientCredentialsSimulation(config));

            // return "ready to go". The simulationId is what the requester will call resume with,
            // so it has to be the session id this simulation is registered under.
            AdditionalInstructions additionalInstructions = new AdditionalInstructions();
            additionalInstructions.setSimulationId(sessionId);

            StringBuilder message = new StringBuilder();
            message.append("Test for the client credentials sequence is initialized and can be started! ");

            if (config.isForExtendedToken())
                message.append("Since the person_id is set, an extended access token will be requested.");
            else
                message.append("Since the person_id is not set, a basic access token will be requested.");

            additionalInstructions.setInstruction(message.toString());
            return additionalInstructions; // new SwitchToExecution();
        }

        if (sequenceId.equals(AUTHORIZATION_CODE_SEQUENCE_ID)) {

            AuthorizationCodeConfig config = new AuthorizationCodeConfig(sessionId, simulationRequest);
            config.redirectUri = redirectUri;
            assertValid(config.validate());

            authorizationCodeSimulations.put(sessionId, new AuthorizationCodeSimulation(config));

            // return "ready to go". The simulationId is what the requester will call resume with,
            // so it has to be the session id this simulation is registered under.
            AdditionalInstructions additionalInstructions = new AdditionalInstructions();
            additionalInstructions.setSimulationId(sessionId);

            StringBuilder message = new StringBuilder();
            message.append("Test for the authorization code sequence is initialized and can be started! ");

            if (config.isForExtendedToken())
                message.append("Since the person_id is set, an extended access token will be requested.");
            else
                message.append("Since the person_id is not set, a basic access token will be requested.");

            additionalInstructions.setInstruction(message.toString());
            return additionalInstructions; // new SwitchToExecution();
        }

        throw new UnknownSequenceException();

    }

    /**
     * A setup that cannot run is refused, so the requester gets 400 Bad Request with the reason
     * instead of instructions followed by a resume that can only fail.
     *
     * @param validation the result of validating a configuration, {@code null} if it is valid
     */
    private static void assertValid(AdditionalInstructions validation) {
        if (validation != null) {
            throw new MissingRequiredParameterException(validation.getInstruction());
        }
    }

    /**
     * Runs the simulation set up under the session id and delivers its report through the callback.
     * <p>
     * The simulation manager calls this on a thread of its own and cancels that thread once the timeout
     * requested at setup has passed, reporting the timeout itself. A run cancelled that way sends
     * nothing: its report would be a second one for the same session.
     *
     * @param sessionId the current test session id
     * @param callback  callback to be notified when the simulation is finished
     */
    @Override
    public void runSimulation(String sessionId, SimulationCallback callback) {

        // a simulation runs at most once, so it leaves the map as it starts
        ClientCredentialsSimulation clientCredentialsSimulation = clientCredentialSimulations.remove(sessionId);
        AuthorizationCodeSimulation authorizationCodeSimulation = authorizationCodeSimulations.remove(sessionId);

        SimulationReport simulationReport;

        if (clientCredentialsSimulation != null) {

            LOG.info("Running clientCredentialsSimulation with session id " + sessionId);
            TransactionReport transactionReport = clientCredentialsSimulation.run();
            ClientCredentialConfig config = clientCredentialsSimulation.getConfig();
            simulationReport = buildReport(sessionId, config.sequenceId, config.simulationParameters, transactionReport);
            LOG.info("Finished clientCredentialsSimulation with session id " + sessionId);

        } else if (authorizationCodeSimulation != null) {

            LOG.info("Running authorizationCodeSimulation with session id " + sessionId);
            TransactionReport transactionReport = authorizationCodeSimulation.run();
            AuthorizationCodeConfig config = authorizationCodeSimulation.getConfig();
            simulationReport = buildReport(sessionId, config.sequenceId, config.simulationParameters, transactionReport);
            LOG.info("Finished authorizationCodeSimulation with session id " + sessionId);

        } else {
            // if neither clientCredentialsSimulation nor authorizationCodeSimulation is setup
            throw new UnknownSimulationException(UnknownSimulationException.BASE_MESSAGE + sessionId);
        }

        if (Thread.currentThread().isInterrupted()) {
            LOG.warn("Simulation with session id " + sessionId + " was cancelled after its timeout, its report is not sent");
            return;
        }

        callback.notifySimulation(simulationReport);
    }

    /**
     * Build the report of a simulation run, which consists of a single transaction.
     *
     * @param sessionId            the current test session id
     * @param sequenceId           the sequence that was run
     * @param simulationParameters the parameters the simulation was set up with
     * @param transactionReport    the report of the transaction
     * @return the simulation report
     */
    private SimulationReport buildReport(String sessionId, String sequenceId, List<Parameter> simulationParameters,
                                         TransactionReport transactionReport) {

        Service service = metadataService.getMetadata();

        SimulationReport simulationReport = new SimulationReport();
        simulationReport.setUuid(sessionId);
        simulationReport.setSequenceId(sequenceId);
        simulationReport.setServiceName(service.getName());
        simulationReport.setDateTime(Instant.now());
        simulationReport.setResult(transactionReport.getResult());
        simulationReport.setTransactionReports(List.of(transactionReport));
        simulationReport.setServiceVersion(service.getVersion());
        simulationReport.setSimulationParameters(simulationParameters);
        return simulationReport;
    }

    /**
     * Periodically removes simulations that were set up but never resumed. A simulation that is
     * resumed leaves the map when it starts running.
     */
    @Scheduled(every = "10s")
    void run() {

        // accepted age of simulations before being removed
        long acceptedDelayInSeconds = 10 * 60;

        for (Map.Entry<String, ClientCredentialsSimulation> entry : clientCredentialSimulations.entrySet()) {

            String sessionId = entry.getKey();
            ClientCredentialsSimulation simulation = entry.getValue();

            // orphaned simulations
            if (simulation.status == Status.READY &&
                    simulation.getCreatedAt().plusSeconds(acceptedDelayInSeconds).isBefore(Instant.now())) {
                LOG.info("Remove orphaned simulation with sessionId = " + sessionId + " and timestamp = " + simulation.getCreatedAt());
                clientCredentialSimulations.remove(sessionId, simulation);
            }
        }
    }

    /**
     * @return the SimulationSequence definition for the IUA Client Credential flow
     */
    public SimulationSequence getClientCredentialSequence() {

        SimulationSequence sequence = new SimulationSequence();
        sequence.setId(CLIENT_CREDENTIAL_SEQUENCE_ID);

        SupportedParameter tokenEndpoint = new SupportedParameter();
        tokenEndpoint.setName("token_endpoint_url").setGroupName("System under test").setType(ParameterType.TEXT);
        tokenEndpoint.setDefaultValue("http://localhost:9000/token").setRequired(true);
        tokenEndpoint.setDescription("The URL of the token endpoint of the system under test.");

        SupportedParameter clientId = new SupportedParameter();
        clientId.setName("client_id").setGroupName("Client credentials").setType(ParameterType.TEXT);
        clientId.setDefaultValue("client-id").setRequired(true);
        clientId.setDescription("The client id of the IUA client simulator.");

        SupportedParameter clientSecret = new SupportedParameter();
        clientSecret.setName("client_secret").setGroupName("Client credentials").setType(ParameterType.TEXT);
        clientSecret.setDefaultValue("client-secret").setRequired(true);
        clientSecret.setDescription("The client secret of the IUA client simulator.");

        SupportedParameter principal = new SupportedParameter();
        principal.setName("principal").setGroupName("Request attributes").setType(ParameterType.TEXT);
        principal.setDefaultValue("principal.name").setRequired(true);
        principal.setDescription("The name of the responsible person for the request.");

        SupportedParameter principalId = new SupportedParameter();
        principalId.setName("principal_id").setGroupName("Request attributes").setType(ParameterType.TEXT);
        principalId.setDefaultValue("principal.id").setRequired(true);
        principalId.setDescription("The GLN of the responsible person for the request.");

        String requestScope = "purpose_of_use=urn:oid:2.16.756.5.30.1.127.3.10.5|AUTO " +
                "subject_role=urn:oid:2.16.756.5.30.1.127.3.10.6|TC";

        SupportedParameter scope = new SupportedParameter();
        scope.setName("scope").setGroupName("Request attributes").setType(ParameterType.TEXT);
        scope.setDefaultValue(requestScope).setRequired(true);
        scope.setDescription("The scope to be requested defining the user role and purpose of use.");

        SupportedParameter personId = new SupportedParameter();
        personId.setName("person_id").setGroupName("Request attributes").setType(ParameterType.TEXT);
        personId.setDefaultValue(SPID).setRequired(false);
        personId.setDescription("The SPID of the patient dossier to be accessed, required for extended access token.");

        // example key to be overridden by the Authorization Server under test.
        String key = SigningKeyHelper.getRSAPublicKey();

        SupportedParameter publicKey = new SupportedParameter();
        publicKey.setName("jwt_public_key").setGroupName("System under test").setType(ParameterType.TEXT);
        publicKey.setDefaultValue(key).setRequired(true);
        publicKey.setDescription("The public key to verify the JWT signature of the system under test.");

        // add parameter to the sequence
        sequence.setSupportedParameters(List.of(
                tokenEndpoint,
                clientId,
                clientSecret,
                scope,
                personId,
                principal,
                principalId,
                publicKey
        ));

        sequence.setTransactions(List.of("Get Access Token [ITI-71]"));
        sequence.setShortDescription("Sequence for the ITI-71 client credential flow.");
        sequence.setDescription(
                "Sequence for the client credential flow of the ITI-71 transaction." +
                        "In this sequence, the client sends a http POST request to the IUA Server to get an access token." +
                        "The http request is signed using using http signature as defined in RFC-9421 the private key of the client simulator."
        );

        sequence.setStandards(List.of(
                "CH:IUA Get Access Token [ITI-71]",
                "RFC-9421 HTTP Message Signatures",
                "OAuth 2.1 draft-ietf-oauth-v2-1-15",
                "RFC 7519 JSON Web Token (JWT)",
                "RFC 7515 JSON Web Signature (JWS)",
                "and Standards referenced therein"
        ));

        // add the tested role
        TestedRole testedRole = new TestedRole();
        testedRole.setName("CH:IUA Server");
        testedRole.setType(RoleType.RESPONDER);
        sequence.setTestedRoles(List.of(testedRole));

        // add the simulationRole
        SimulatedRole simulationRole = new SimulatedRole();
        simulationRole.setName("CH:IUA Client");
        simulationRole.setType(RoleType.INITIATOR);
        sequence.setSimulatedRoles(List.of(simulationRole));

        // add the public keys as read-only parameter to simulationRole
        try{

            Parameter httpSignaturePublicKey = new Parameter();
            httpSignaturePublicKey.setName("http_signature_public_key").setType(ParameterType.TEXT);
            httpSignaturePublicKey.setValue(SigningKeyHelper.getEcPublicKeyJWK().toJSONString());

            Parameter idPSignaturePublicKey = new Parameter();
            idPSignaturePublicKey.setName("idp_signature_public_key").setType(ParameterType.TEXT);
            idPSignaturePublicKey.setValue(SigningKeyHelper.getRSAPublicKeyJWK().toJSONString());

            simulationRole.setConfigs(List.of(httpSignaturePublicKey, idPSignaturePublicKey));

        } catch (ParseException e) {
            LOG.error("Failed to create public keys.", e);
            throw new RuntimeException(e);
        }

        LOG.info("Return the Client Credential Flow Sequence: " + sequence);
        return sequence;
    }


    /**
     * @return the SimulationSequence definition for the IUA Client Credential flow
     */
    public SimulationSequence getAuthorizationCodeSequence() {

        SimulationSequence sequence = new SimulationSequence();
        sequence.setId(AUTHORIZATION_CODE_SEQUENCE_ID);

        SupportedParameter codeEndpoint = new SupportedParameter();
        codeEndpoint.setName("code_endpoint_url").setGroupName("System under test").setType(ParameterType.TEXT);
        codeEndpoint.setDefaultValue("http://localhost:9000/authorize").setRequired(true);
        codeEndpoint.setDescription("The URL of the code endpoint of the system under test.");

        SupportedParameter tokenEndpoint = new SupportedParameter();
        tokenEndpoint.setName("token_endpoint_url").setGroupName("System under test").setType(ParameterType.TEXT);
        tokenEndpoint.setDefaultValue("http://localhost:9000/token").setRequired(true);
        tokenEndpoint.setDescription("The URL of the token endpoint of the system under test.");

        SupportedParameter clientId = new SupportedParameter();
        clientId.setName("client_id").setGroupName("Client credentials").setType(ParameterType.TEXT);
        clientId.setDefaultValue("client-id").setRequired(true);
        clientId.setDescription("The client id of the IUA client simulator.");

        SupportedParameter clientSecret = new SupportedParameter();
        clientSecret.setName("client_secret").setGroupName("Client credentials").setType(ParameterType.TEXT);
        clientSecret.setDefaultValue("client-secret").setRequired(true);
        clientSecret.setDescription("The client secret of the IUA client simulator.");

        // the scope to be overridden in th test setup.
        String requestScope = "purpose_of_use=urn:oid:2.16.756.5.30.1.127.3.10.5|NORMAL " +
                "subject_role=urn:oid:2.16.756.5.30.1.127.3.10.6|HCP";

        SupportedParameter scope = new SupportedParameter();
        scope.setName("scope").setGroupName("Request attributes").setType(ParameterType.TEXT);
        scope.setDefaultValue(requestScope).setRequired(true);
        scope.setDescription("The scope to be requested defining the user role and purpose of use.");

        // the patient epr to be accessed, required for extended access token
        SupportedParameter personId = new SupportedParameter();
        personId.setName("person_id").setGroupName("Request attributes").setType(ParameterType.TEXT);
        personId.setDefaultValue(SPID).setRequired(false);
        personId.setDescription("The SPID of the patient dossier to be accessed, required for extended access token.");

        // principal claim, only for role ASS
        SupportedParameter principal = new SupportedParameter();
        principal.setName("principal").setGroupName("Request attributes").setType(ParameterType.TEXT);
        principal.setDefaultValue("principal.name").setRequired(false);
        principal.setDescription("The name of the responsible person for the request. Required for assistants with role ASS.");

        SupportedParameter principalId = new SupportedParameter();
        principalId.setName("principal_id").setGroupName("Request attributes").setType(ParameterType.TEXT);
        principalId.setDefaultValue("principal.id").setRequired(false);
        principalId.setDescription("The GLN of the responsible person for the request. Required for assistants with role ASS.");

        // optional group claim, only for role HCP and ASS
        SupportedParameter group = new SupportedParameter();
        group.setName("group").setGroupName("Request attributes").setType(ParameterType.TEXT);
        group.setDefaultValue("group.name").setRequired(false);
        group.setDescription("The name of the institution or group the request ist performed on behalf. Optional for role HCP and ASS.");

        SupportedParameter groupId = new SupportedParameter();
        groupId.setName("group_id").setGroupName("Request attributes").setType(ParameterType.TEXT);
        groupId.setDefaultValue("group.id").setRequired(false);
        groupId.setDescription("The OID of the institution or group the request ist performed on behalf. Optional for role HCP and ASS.");

        // example key to be overridden by the Authorization Server under test.
        String key = SigningKeyHelper.getRSAPublicKey();

        SupportedParameter serverPublicKey = new SupportedParameter();
        serverPublicKey.setName("jwt_public_key").setGroupName("System under test").setType(ParameterType.TEXT);
        serverPublicKey.setDefaultValue(key).setRequired(true);
        serverPublicKey.setDescription("The public key to verify the JWT signature of the system under test.");

        // add supported parameter to be set by the SUT
        sequence.setSupportedParameters(List.of(
                codeEndpoint,
                tokenEndpoint,
                clientId,
                clientSecret,
                scope,
                personId,
                principal,
                principalId,
                group,
                groupId,
                serverPublicKey));

        SimulatedRole simulationRole = new SimulatedRole();
        simulationRole.setName("CH:IUA Client");
        simulationRole.setType(RoleType.INITIATOR);
        sequence.setSimulatedRoles(List.of(simulationRole));

        // add the public keys as read only parameter to sumulationRole

        TestedRole testedRole = new TestedRole();
        testedRole.setName("CH:IUA Server");
        testedRole.setType(RoleType.RESPONDER);
        sequence.setTestedRoles(List.of(testedRole));

        sequence.setStandards(List.of(
                "CH:IUA Get Access Token [ITI-71]",
                "RFC-9421 HTTP Message Signatures",
                "OAuth 2.1 draft-ietf-oauth-v2-1-15",
                "RFC 7519 JSON Web Token (JWT)",
                "RFC 7515 JSON Web Signature (JWS)",
                "and Standards referenced therein"
        ));

        sequence.setTransactions(List.of("Get Access Token [ITI-71]"));

        sequence.setShortDescription("Sequence for the ITI-71 authorization code flow.");

        sequence.setDescription(
                "Sequence for the authorization code flow of the ITI-71 transaction." +
                        "In this sequence, the client first sends a http Get request to the IUA Server to get an authorization code." +
                        "In the second step the client sends a http POST request to the IUA Server to exchange the authorization code to an access token." +
                        "The second http request is signed using http signature as defined in RFC-9421 with the private key of the simulator."
        );

        LOG.info("Return the Authorization Code Flow Sequence: " + sequence);
        return sequence;
    }
}
